### ISSUE TITLE
NagAconda install throwing error

### ISSUE THREAD

**Issue by rajcybage** [bonesmoses/NagAconda#4]
C:\Python33>"c:\python33\scripts\pip.exe" install NagAconda
Downloading/unpacking NagAconda
  Downloading NagAconda-0.2.1.tar.gz (235kB): 235kB downloaded
  Running setup.py egg_info for package NagAconda
    Traceback (most recent call last):
      File "<string>", line 16, in <module>
      File "c:\users\rajars~1\appdata\local\temp\pip_build_rajarshid\NagAconda\setup.py", line 4, in <module>
        import NagAconda
      File ".\NagAconda__init__.py", line 19, in <module>
        from Plugin import *
    ImportError: No module named 'Plugin'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 16, in <module>

  File "c:\users\rajars~1\appdata\local\temp\pip_build_rajarshid\NagAconda\setup.py", line 4, in <module>

```
import NagAconda
```

  File ".\NagAconda__init__.py", line 19, in <module>

```
from Plugin import *
```

ImportError: No module named 'Plugin'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in c:\users\rajars~1\appdata\local\temp\pip_build_rajarshid\NagAconda
Storing complete log in C:\Users\rajarshid\pip\pip.log

C:\Python33>pause
Press any key to continue . . .

**Comment by SchlegelS0208** [comment]
Fixed with:
https://github.com/bonesmoses/NagAconda/pull/12/files#diff-5e1a72a8d4b9a8dbc485830f981fd4d12e1e3beb616cdf858fca4dd887b4b248L19

Pull-Request was made for getting things into the year 2022 ...
